version: '3'
services:
  db:
    image: postgres:17
    volumes:
      - ./docker/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: >
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
      -c hba_file=/etc/postgresql/pg_hba.conf
    environment:
      - 'POSTGRES_PASSWORD=jenkinsuplink'
      # Used for psql non-interactive scripting
      - 'PGPASSWORD=jenkinsuplink'
      - 'POSTGRES_DB=uplink_development'

  node:
    image: node:22
    command: '/usr/local/bin/node $PWD/node_modules/.bin/nodemon build'
    working_dir: $PWD
    environment:
      - 'PATH=$PWD/node_modules/.bin:$PATH'
      - 'NODE_ENV=$NODE_ENV'
      - 'DB_TRACING=true'
      - 'DEBUG=$DEBUG'
      - 'SENTRY_DSN=$SENTRY_DSN'
    volumes:
      - $PWD:$PWD
    ports:
      - '3030:3030'
    depends_on:
      - db
